### ISSUE TITLE
[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by deepseafish** [bmcorser/pelicanfly#11]
I'm getting this error when installing the plugin as recommended and importing it like this: 
PLUGINS = [ 'pelicanfly']

Full error:
RITICAL: [Errno 2] No such file or directory: u'<myblogfolder>/output/theme/css/main.css'

I'm generating my blog on OS X Yosemite.

Other plugins seem to work fine

**Comment by bmcorser** [comment]
I haven't maintained pelicanfly in some time, but not sure if this issue is related to pelicanfly. Perhaps your output path is set to `/output`?

**Comment by deepzeafish** [comment]
I'm not setting the output path at all

**Comment by bmcorser** [comment]
Can you tell me what version of pelican you're using and maybe put your config in a gist and I'll try and have a look this evening.

**Comment by deepzeafish** [comment]
Thanks a lot, here's the gist: https://gist.github.com/deepzeafish/0b35baa9989aed7b5295

This is the errormessage: [Errno 2] No such file or directory: u'/Users/deepzeafish/mysite/output/theme/css/main.css'

I checked the whole mysite for main.css, it's mentioned nowhere. When creating the content I use the --ignore-cache -d options.

**Comment by bmcorser** [comment]
Having difficultly reproducing this. I ran through the [quickstart tutorial](http://docs.getpelican.com/en/3.5.0/quickstart.html), you can see the commands I used [here](https://gist.github.com/bmcorser/4c0b8998c626b50e8acd) and didn't get any errors.

Can you put the project you're trying to build somewhere I can see it (make a repo on GitHub?) I can try and reproduce your set up more precisely.

**Comment by bmcorser** [comment]
Just to note, if you [search](https://github.com/getpelican/pelican/search?utf8=%E2%9C%93&q=main.css&type=Code) for `main.css` in the pelican repo, it is mentioned frequently.

**Comment by deepzeafish** [comment]
Thanks for your offer, but as the problem seems to be on my side you shouldn't do my debugging ;-)
I'll look into it tonight and let you know if I find something interesting.
