### ISSUE TITLE
pelicanfly in PyPI is still using FontAwesome 4.0.3

### ISSUE THREAD

**Issue by ronanpaixao** [bmcorser/pelicanfly#12]
When downloading pelicanfly with `pip` I was surprised to be unable to use more recent icons. Investigation showed that:

1) pelicanfly is overriding my theme's (bootstrap3) font-awesome CSS files. This replaces the theme's 4.3.0 CSS with an outdated 4.0.3 one.

2) pelicanfly in GitHub does contain updated 4.3.0 files. However, the version stated in setup.py is the same as the one in PyPI. Maybe there should have been a minor version bump and new upload to PyPI.

The workaround for now is doing:
```
pip uninstall pelicanfly
pip install git+git://github.com/bmcorser/pelicanfly.git
```

PS: Font Awesome has already released version 4.4.

**Comment by bmcorser** [comment]
#14 and https://pypi.python.org/pypi/pelicanfly/0.4.3 should close this `:)`
