### ISSUE TITLE
Need example for expanded font

### ISSUE THREAD

**Issue by tiarno** [bmcorser/pelicanfly#8]
If there is a syntax to get the expanded version of an icon, an example should be added.
By expanded, I mean this type of syntax that works in the RST version:

:fa:`fa-github fa-4x`

That example produces the github icon at 4 times normal size. Is there a way to do that with pelicanfly?

**Comment by lgwapnitsky** [comment]
don't see why this is closed.  pelican_fontawesome isn't working, but allows for this. Sometimes you just need a larger icon for emphasis

**Comment by bmcorser** [comment]
:ghost:
